---
- name: Execute a command silently on remote machines
  hosts: ubuntu1, ubuntu2
  become: true

  tasks:
    - name: Ubuntu Stop SSH Service
      ansible.builtin.service:
        name: ssh
        state: stopped