---
- name: Fix MySQL Port and Restart Service
  hosts: dev
  become: yes
  gather_facts: no
  tasks:
    - name: Change MySQL Server port back to default (3306)
      replace:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^port\s*=\s*\d+'
        replace: 'port = 3306'
      notify: Restart MySQL

    - name: Ensure MySQL configuration is correct
      command: "mysqld --validate-config"
      register: mysql_config_check
      changed_when: false
      failed_when: mysql_config_check.rc != 0
  handlers:
    - name: Restart MySQL
      systemd:
        name: mysql
        state: restarted
