---
- name: Execute a command silently on remote machines
  hosts: ubuntu1, ubuntu2
  become: true
  gather_facts: no

  tasks:
    - name: Ubuntu Start SSH Service
      ansible.builtin.service:
        name: ssh
        state: started