---
- name: Change SSH port to one of the specified ports on remote machines
  hosts: ubuntu1, ubuntu2
  become: true
  gather_facts: no

  tasks:
    - name: Set SSH port variable
      set_fact:
        ssh_ports:
          - 22
          - 25565

    - name: Update SSH port in sshd_config for each port
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?Port'
        line: "Port 22
      loop: "{{ ssh_ports }}"

    - name: Restart SSH service to apply changes
      ansible.builtin.service:
        name: ssh
        state: restarted
