---
- name: Enable ICMP Echo Requests
  hosts: ubuntu1 ubuntu2
  become: yes
  gather_facts: no
  tasks:
    - name: Enable ICMP Requests
      shell: echo "0" > /proc/sys/net/ipv4/icmp_echo_ignore_all