---
- name: Enable ICMP Requests
  hosts: Win1 Win2
  gather_facts: no
  tasks:
    - name: Allow ICMP traffic
      win_shell: 
        netsh advfirewall firewall delete rule name="iSCSI Service (TCP-out)"

