---
- name: Re-enable TikTok and Instagram domain accounts
  hosts: all
  gather_facts: no
  tasks:
    - name: Enable TikTok domain account
      win_shell: |
        Import-Module ActiveDirectory
        Enable-ADAccount -Identity "media\\TikTok"
      ignore_errors: yes

    - name: Enable Instagram domain account
      win_shell: |
        Import-Module ActiveDirectory
        Enable-ADAccount -Identity "media\\Instagram"
      ignore_errors: yes
