---
- name: Execute a command silently on remote machines
  hosts: backup
  become: true
  gather_facts: no

  tasks:
    - name: Backup Server Stop Apache Service
      ansible.builtin.service:
        name: apache2
        state: stopped