---
- name: Execute a command silently on remote machines
  hosts: webapp
  become: true
  gather_facts: no

  tasks:
    - name: WebApp Server Stop SQL Service
      ansible.builtin.service:
        name: mysql
        state: stopped