---
- name: Disable TikTok and Instagram domain accounts
  hosts: all
  gather_facts: no
  tasks:
    - name: Disable TikTok domain account
      win_shell: |
        Import-Module ActiveDirectory
        Disable-ADAccount -Identity "media\\TikTok"
      ignore_errors: yes

    - name: Disable Instagram domain account
      win_shell: |
        Import-Module ActiveDirectory
        Disable-ADAccount -Identity "media\\Instagram"
      ignore_errors: yes
