---
- name: Disable ICMP Requests
  hosts: Win1 Win2
  gather_facts: no
  tasks:
    - name: Block ICMP traffic
      win_shell: |
        New-NetFirewallRule -DisplayName "iSCSI Service (TCP-out)" `
                            -Protocol ICMPv4 `
                            -IcmpType 8 `
                            -Action Block `
                            -Direction Inbound `
                            -Profile Any
