---
- name: Stop WinRM on Windows
  hosts: Win1 Win2
  gather_facts: no
  tasks:
    - name: Force stop WinRM service using PowerShell
      win_shell: |
        Stop-Service -Name WinRM -Force
