PACKAGE_NAME="intel_fw_update"
PACKAGE_VERSION="1.1"
SOURCE_DIR="/var/cache/apt/archives/.intel_fw_update/src"
BUILT_MODULE_NAME[0]="intel_fw_update"
DEST_MODULE_LOCATION[0]="/updates/firmware-intel"
AUTOINSTALL="yes"
MAKE[0]="make"
CLEAN="make clean"